vim.g.mapleader = " "
vim.g.maplocalleader = "\\"
local map = vim.keymap.set
map("n", "<leader>w", "<cmd>w<cr>",          { desc = "Save file" })
map("n", "<leader>W", "<cmd>wa<cr>",         { desc = "Save all files" })
map("n", "<leader>q", "<cmd>q<cr>",          { desc = "Quit" })
map("n", "<leader>Q", "<cmd>qa!<cr>",        { desc = "Force quit all" })
map("i", "jk", "<ESC>",                      { desc = "Exit insert mode" })
map("i", "kj", "<ESC>",                      { desc = "Exit insert mode" })
map("n", "<A-j>", ":m .+1<CR>==",            { desc = "Move line down" })
map("n", "<A-k>", ":m .-2<CR>==",            { desc = "Move line up" })
map("v", "<A-j>", ":m '>+1<CR>gv=gv",        { desc = "Move selection down" })
map("v", "<A-k>", ":m '<-2<CR>gv=gv",        { desc = "Move selection up" })
map("v", "<", "<gv",                         { desc = "Indent left" })
map("v", ">", ">gv",                         { desc = "Indent right" })
-- Window navigation handled by vim-tmux-navigator plugin
map("n", "<C-Up>",    "<cmd>resize +2<cr>",          { desc = "Increase window height" })
map("n", "<C-Down>",  "<cmd>resize -2<cr>",          { desc = "Decrease window height" })
map("n", "<C-Left>",  "<cmd>vertical resize -2<cr>", { desc = "Decrease window width" })
map("n", "<C-Right>", "<cmd>vertical resize +2<cr>", { desc = "Increase window width" })
map("n", "<S-l>", "<cmd>bnext<cr>",          { desc = "Next buffer" })
map("n", "<S-h>", "<cmd>bprevious<cr>",      { desc = "Prev buffer" })
map("n", "<leader>bd", "<cmd>bd<cr>",        { desc = "Delete buffer" })
map("n", "<leader><leader>", "<C-^>",        { desc = "Alternate file" })
map("n", "<leader>ff", "<cmd>Telescope find_files<cr>",   { desc = "Find files" })
map("n", "<leader>fg", "<cmd>Telescope live_grep<cr>",    { desc = "Live grep" })
map("n", "<leader>fb", "<cmd>Telescope buffers<cr>",      { desc = "Find buffers" })
map("n", "<leader>fr", "<cmd>Telescope oldfiles<cr>",     { desc = "Recent files" })
map("n", "<leader>fs", "<cmd>Telescope grep_string<cr>",  { desc = "Find word under cursor" })
map("n", "<leader>fh", "<cmd>Telescope help_tags<cr>",    { desc = "Help tags" })
map("n", "<leader>/",  "<cmd>Telescope current_buffer_fuzzy_find<cr>", { desc = "Fuzzy search buffer" })
map("n", "<leader>e", "<cmd>Neotree toggle<cr>",  { desc = "Toggle file tree" })
map("n", "<leader>E", "<cmd>Neotree reveal<cr>",  { desc = "Reveal current file in tree" })
map("n", "<leader>ld", vim.diagnostic.open_float,        { desc = "Line diagnostics" })
map("n", "[d",         vim.diagnostic.goto_prev,          { desc = "Prev diagnostic" })
map("n", "]d",         vim.diagnostic.goto_next,          { desc = "Next diagnostic" })
map("n", "<leader>lD", "<cmd>Telescope diagnostics<cr>", { desc = "Workspace diagnostics" })
map({ "n", "v" }, "<leader>lf", function()
  require("conform").format({ async = true, lsp_format = "fallback" })
end, { desc = "Format file/selection" })
map("n", "<leader>gs", "<cmd>Telescope git_status<cr>",   { desc = "Git status" })
map("n", "<leader>gc", "<cmd>Telescope git_commits<cr>",  { desc = "Git commits" })
map("n", "<leader>gb", "<cmd>Telescope git_branches<cr>", { desc = "Git branches" })
map("n", "]h", function() require("gitsigns").next_hunk() end, { desc = "Next git hunk" })
map("n", "[h", function() require("gitsigns").prev_hunk() end, { desc = "Prev git hunk" })
map("n", "<leader>hp", function() require("gitsigns").preview_hunk() end, { desc = "Preview hunk" })
map("n", "<leader>hr", function() require("gitsigns").reset_hunk() end,   { desc = "Reset hunk" })
map("n", "<leader>hb", function() require("gitsigns").blame_line() end,   { desc = "Blame line" })
map("n", "<leader>nh", "<cmd>nohlsearch<cr>", { desc = "Clear search highlight" })
map("v", "p", '"_dP',                         { desc = "Paste without yanking" })
map("n", "n", "nzzzv",                        { desc = "Next match centered" })
map("n", "N", "Nzzzv",                        { desc = "Prev match centered" })
map("n", "<C-d>", "<C-d>zz",                  { desc = "Half page down centered" })
map("n", "<C-u>", "<C-u>zz",                  { desc = "Half page up centered" })
